apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: {{ .Values.global.environment.namespace }}
  name: "{{ .Values.global.environment.name }}-letsencrypt-issuer"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.letsEncryptIssuer }}
    privateKeySecretRef:
      name: "{{ .Values.global.environment.name }}-letsencrypt-issuer"
    solvers:
    - http01:
        ingress:
          class: traefik