services:
  soroban-security-portal-api:
    image: soroban-security-portal-api-local
    build:
      context: .
      dockerfile: SorobanSecurityPortalApi/Dockerfile
    environment:
      - AUTHSECURITYKEY=Yh2k7QSu4l8CZg5p6X3Pna9L0Miy4D3Bvt0JVr87UcOj69Kqw5R2Nmf4FWs03Hdx
    pull_policy: build