services:
  soroban-security-portal-api:
    image: soroban-security-portal-api:latest
    restart: always
    container_name: soroban-security-portal-api
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DBSERVER=host.docker.internal
      - DBPORT=5449
      - DBNAME=sorobansecurityportal
      - DBUSER=admin@sorobansecurity.com
      - DBPASSWORD=SorobanSecurityPortalIsTheBest!
      - DBTIMEOUT=30000
      - DBPGPOOLSIZE=30
      - DBCONNECTIONTIMEOUT=300
      - QDRANTURL=http://host.docker.internal:6348
      - PROXY=
      - TOKENEXPIRATIONTIMEMINUTES=60
      - AUTHISSUER=SorobanSecurityPortal
      - AUTHAUDIENCE=SorobanSecurityPortalClient
      - AUTHSECURITYKEY=${AUTHSECURITYKEY}
      - APPURL=http://localhost:7848/api/v1
      - LOGLEVEL=Debug
      - DISTRIBUTEDCACHEURL=host.docker.internal:6479
      - DISTRIBUTEDCACHEPASSWORD=SorobanSecurityPortalIsTheBest!
      - GOOGLECLIENTID=${GOOGLECLIENTID}
      - GOOGLECLIENTSECRET=${GOOGLECLIENTSECRET}
    ports:
      - "7848:80"
    networks:
      - soroban-security-portal-network

  soroban-security-portal-db:
    container_name: soroban-security-portal-db
    image: pgvector/pgvector:0.8.0-pg17
    restart: always
    environment:
      - POSTGRES_PASSWORD=SorobanSecurityPortalIsTheBest!
      - POSTGRES_USER=admin@sorobansecurity.com
      - POSTGRES_DB=sorobansecurityportal
      - PGDATA=/data/postgres
    command:
      - -c
      - work_mem=32MB
      - -c
      - maintenance_work_mem=256MB
      - -c
      - shared_buffers=1GB
    volumes:
      - soroban-security-portal-db-vector-volume:/data/postgres
      - soroban-security-portal-default-db-vector-volume:/var/lib/postgresql/data
    shm_size: 1gb
    ports:
      - "5449:5432"
    networks:
      - soroban-security-portal-network
      
  soroban-security-portal-qdrant:
    image: qdrant/qdrant:v1.9.2
    restart: always
    container_name: soroban-security-portal-qdrant
    ports:
      - "6348:6333"
      - "6349:6334"
    volumes:
      - soroban-security-portal-qdrant-db-volume:/qdrant/storage
    networks:
      - soroban-security-portal-network
      
  soroban-security-portal-cache:
    image: redis:latest
    container_name: soroban-security-portal-cache
    command: ["redis-server", "--requirepass", "SorobanSecurityPortalIsTheBest!"]
    ports:
      - "6479:6379"
    environment:
      - REDIS_USERNAME=admin@sorobansecurity.com
      - REDIS_PASSWORD=SorobanSecurityPortalIsTheBest!
    networks:
      - soroban-security-portal-network

volumes:
  soroban-security-portal-db-vector-volume:
  soroban-security-portal-default-db-vector-volume:
  soroban-security-portal-qdrant-db-volume:
networks:
  soroban-security-portal-network:
    driver: bridge