import { UserBadge, BadgeCategory, BadgeRarity } from '../api/soroban-security-portal/models/badge';

export const MOCK_BADGES: UserBadge[] = [
    {
        id: '1',
        name: 'First Comment',
        description: 'Made your first comment on a vulnerability report',
        category: BadgeCategory.ACHIEVEMENT,
        rarity: BadgeRarity.COMMON,
        icon: '💬',
        color: '#4CAF50',
        awardedAt: new Date('2024-01-15'),
        isLocked: false,
    },
    {
        id: '2',
        name: '10 Reports',
        description: 'Submitted 10 vulnerability reports',
        category: BadgeCategory.CONTRIBUTION,
        rarity: BadgeRarity.RARE,
        icon: '🔍',
        color: '#2196F3',
        awardedAt: new Date('2024-02-20'),
        isLocked: false,
    },
    {
        id: '3',
        name: 'Security Expert',
        description: 'Identified a critical vulnerability',
        category: BadgeCategory.ACHIEVEMENT,
        rarity: BadgeRarity.EPIC,
        icon: '🛡️',
        color: '#9C27B0',
        awardedAt: new Date('2024-03-10'),
        isLocked: false,
    },
    {
        id: '4',
        name: 'Community Leader',
        description: 'Helped 50+ users with security questions',
        category: BadgeCategory.SPECIAL,
        rarity: BadgeRarity.LEGENDARY,
        icon: '👑',
        color: '#FF9800',
        awardedAt: new Date('2024-04-05'),
        isLocked: false,
    },
    {
        id: '5',
        name: 'Code Reviewer',
        description: 'Review 25 audit reports',
        category: BadgeCategory.CONTRIBUTION,
        rarity: BadgeRarity.RARE,
        icon: '📝',
        color: '#2196F3',
        awardedAt: new Date(),
        isLocked: true,
        progress: 60,
    },
    {
        id: '6',
        name: 'Bug Hunter',
        description: 'Find 5 critical bugs',
        category: BadgeCategory.ACHIEVEMENT,
        rarity: BadgeRarity.EPIC,
        icon: '🐛',
        color: '#9C27B0',
        awardedAt: new Date(),
        isLocked: true,
        progress: 40,
    },
];
