apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-sorobansecurityportal-api-ip"
spec:
  selector:
    app: "{{ .Values.global.environment.name }}-sorobansecurityportal-api"
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080