apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-sorobansecurityportal-postgres-secret"
type: Opaque
data:
  userName: {{ .Values.global.postgres.userName | b64enc | quote }}
  {{ if .Values.global.postgres.password }}
  password: {{ .Values.global.postgres.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 32 }}
  {{ end }}