apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.environment.namespace }}"
  name: "{{ .Values.global.environment.name }}-sorobansecurityportal-qdrant-loadbalancer"
spec:
  selector:
    app: "{{ .Values.global.environment.name }}-sorobansecurityportal-qdrant"
  type: ClusterIP
  ports:
    - port: 6333
      targetPort: 6333